// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
// /

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwJgfj_lGLCmn3yaPfOBbDjtiEEOUShY',
    appId: '1:812614656044:web:ae0723ad9cfe40f0d9f189',
    messagingSenderId: '812614656044',
    projectId: 'first-aid-chat',
    authDomain: 'first-aid-chat.firebaseapp.com',
    storageBucket: 'first-aid-chat.appspot.com',
    measurementId: 'G-ZQG3R6G4EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhrTMjld_NkNdTWO5C_jy-kX-HejuofFQ',
    appId: '1:812614656044:android:06b43136df6ffcf5d9f189',
    messagingSenderId: '812614656044',
    projectId: 'first-aid-chat',
    storageBucket: 'first-aid-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmscbMSRykZA4GOi90kgCz1I9df0rIaF0',
    appId: '1:812614656044:ios:764a9e4c0f611223d9f189',
    messagingSenderId: '812614656044',
    projectId: 'first-aid-chat',
    storageBucket: 'first-aid-chat.appspot.com',
    iosClientId:
        '812614656044-9lu19bfp918ctn81clpkf2jf21ih1fpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstAidChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmscbMSRykZA4GOi90kgCz1I9df0rIaF0',
    appId: '1:812614656044:ios:764a9e4c0f611223d9f189',
    messagingSenderId: '812614656044',
    projectId: 'first-aid-chat',
    storageBucket: 'first-aid-chat.appspot.com',
    iosClientId:
        '812614656044-9lu19bfp918ctn81clpkf2jf21ih1fpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstAidChat',
  );
}
